name: SaplimgX
version: '${project.version}'
main: saplimgx.untitled.Plugin
api-version: 1.19

commands:
  Fly:
    description: Toggles Fly
    usage:  /fly
    aliases: f
    permission: fly
    permission-message: You do not have permission
  GM:
    description: Toggles Fly
    usage: /fly
    aliases: f
    permission: fly
    permission-message: You do not have permission
